version: 2

project_name: local

builds:
  - id: local
    main: ./cmd/local
    binary: local
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

homebrew_casks:
  - name: local
    repository:
      owner: kimaguri
      name: homebrew-simplx-toolkit
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    url:
      verified: github.com/kimaguri/simplx-toolkit
    homepage: "https://github.com/kimaguri/simplx-toolkit"
    description: "Dev process dashboard TUI — launch, monitor, and manage local dev services"

release:
  github:
    owner: kimaguri
    name: simplx-toolkit
